name: Repository Dispatch
on:
  repository_dispatch:
    types: [new-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo hello world
  myOtherEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: mark-hartmann/update-deployment-action@develop
        with:
          image: markhartmann/mstp-service123 
          release: ${{ github.event.client_payload.ref }}
          deployment-manifest: src/test 
