name: Repository Dispatch
on:
  repository_dispatch:
    types: [new-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mstp-master
        uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo hello world
      - name: Apply the new tag to the deployment
        uses: mark-hartmann/update-deployment-action@develop
        with:
          tag: ${{ github.event.client_payload.ref }}
          name: auth 
          deployment: mstp-deployment.yaml 
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
